### ISSUE TITLE
Unexported interface incorrectly listed

### ISSUE THREAD

**Issue by johanbrandhorst** [c4s4/gointerfaces#1]
Hi,

Great project! I was going through the list and noticed an interface called simply `I`. I went to the source (https://github.com/golang/go/blob/go1.10.1/src/net/http/h2_bundle.go#L6576) and found it's an unexported interface. I'm assuming the parser will need to check if the interface is defined in the top scope before determining to list it.

**Comment by c4s4** [comment]
Thank you for your feedback. This bug was fixed in latest release 1.10.2.
